#!/bin/bash

# postinst
#
# Copyright (C) 2018 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#

case "$1" in
    configure)

        # Enable the systemd service
        systemctl enable kano-os-recovery
        ;;

esac

#DEBHELPER#

exit 0
